name = "Testing 3.3 Power Machines AE2"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ce6a1f177ce88ee42b9108c20410f6407c068304bc48c4818bdfd9646353bb8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
