name = "Testing 3.3 Power Machines AE2"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58431e165dff2d7501e54ea221b268557d606ca080bbfba38b673219dad1bf2d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
