name = "Testing 3.3 Power Machines AE2"
author = "Dartis_Xui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d601ba684c6d3a4b53f76e3bbb08de4659bbd5fd29b88240c8f708d3a37af9ef"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
